# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20425e9fcc76a9ac5561e1d95ed29d5ccd47a552a5581e226fd093f6a53c2086f83c61b4010b9d0e7d6e48e1ec9115a56c3e89a4d185764cbb1950c29c7db614

test:
  secret_key_base: d35aa6cccdff6fe233624804a91211f1e53b1e5ef3ec3b8f985a2e74c41d9d9b3364970919c6e81618f503caf509681961af0c48f5f1fce0393f3581a5f5811e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:

secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
